# Generated by Django 4.2.20 on 2025-09-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_insurance_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='additional_tariffs',
            field=models.ManyToManyField(blank=True, related_name='users_additional_tariffs', to='users.tariff'),
        ),
    ]
