# Generated by Django 4.2.20 on 2025-09-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_additional_tariffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
