# Generated by Django 4.2.20 on 2025-10-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_insurance_number_customuser_monthly_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='additional_tariffs',
            field=models.ManyToManyField(blank=True, to='users.tariff'),
        ),
    ]
