"""
Django settings for pkv_backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see:
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse
from dotenv import load_dotenv
import dj_database_url

# Load environment variables from .env file
load_dotenv()

# Base directory of the project (two levels up from this file)
BASE_DIR = Path(__file__).resolve().parent.parent


# ------------------------------------------------------------------------------
# Quick-start development settings - NOT suitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
# ------------------------------------------------------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: do NOT run with debug enabled in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"

# Allowed CORS origins (comma-separated in env variable)
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",") if o.strip()
]

# Allowed hosts for this Django instance
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")


# ------------------------------------------------------------------------------
# Static and Media files
# ------------------------------------------------------------------------------

# URL prefix for static files
STATIC_URL = '/static/'

# Directory where static files are collected for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Use WhiteNoise for efficient static file serving
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media (uploaded files) configuration
MEDIA_URL = '/contracts/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'contracts')


# ------------------------------------------------------------------------------
# Custom user model
# ------------------------------------------------------------------------------

AUTH_USER_MODEL = 'users.CustomUser'


# ------------------------------------------------------------------------------
# Application definition
# ------------------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'django_extensions',
    'corsheaders',

    # Local apps
    'documents',
    'users',
]

MIDDLEWARE = [
    # WhiteNoise must come first to serve static files correctly
    'whitenoise.middleware.WhiteNoiseMiddleware',

    # CORS handling
    "corsheaders.middleware.CorsMiddleware",

    # Standard Django middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

ROOT_URLCONF = 'pkv_backend.urls'

# Template configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pkv_backend.wsgi.application'


# ------------------------------------------------------------------------------
# Database configuration
# ------------------------------------------------------------------------------

# Parse DATABASE_URL (used mainly for validation / debugging)
tmpPostgres = urlparse(os.getenv("DATABASE_URL"))

# Database configuration using dj-database-url
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get("DATABASE_URL"),
        conn_max_age=600,
        ssl_require='require'  # Required for Neon / managed Postgres
    )
}


# ------------------------------------------------------------------------------
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
# ------------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ------------------------------------------------------------------------------
# Internationalization
# ------------------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = True


# ------------------------------------------------------------------------------
# Default primary key field type
# ------------------------------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ------------------------------------------------------------------------------
# Email (SMTP) configuration
# ------------------------------------------------------------------------------

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_USER_1")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASSWORD_1")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

# Frontend domain (used for links in emails, etc.)
FRONTEND_DOMAIN = os.getenv("FRONTEND_DOMAIN", "")

# Uncomment for local testing:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# ------------------------------------------------------------------------------
# CSRF & CORS configuration
# ------------------------------------------------------------------------------

# Trusted origins for CSRF protection
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]


# ------------------------------------------------------------------------------
# HTTPS & Security settings (Production)
# ------------------------------------------------------------------------------

# Force HTTPS redirect (only active when DEBUG=False)
SECURE_SSL_REDIRECT = os.getenv("DJANGO_DEBUG", "False") != "True"

# Trust reverse proxy header for SSL (IMPORTANT for hosting providers)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# HTTP Strict Transport Security (HSTS)
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Cookie security: only send cookies via HTTPS in production
SESSION_COOKIE_SECURE = os.getenv("DJANGO_DEBUG", "False") != "True"
CSRF_COOKIE_SECURE = os.getenv("DJANGO_DEBUG", "False") != "True"


# ------------------------------------------------------------------------------
# Logging configuration
# ------------------------------------------------------------------------------

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}
